services:
  api:
    container_name: pokerhand-api
    build:
      context: .
      dockerfile: Dockerfile
      target: api-dev
    restart: unless-stopped

    volumes:
      - ./api:/app:cached
    command: air
    ports:
      - "8080:8080"
