name: Test, Lint & Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "api/go.mod"
      - run: make test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: api
          version: v1.60

  build:
    needs: [test, lint]
    name: Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        uses: ko-build/setup-ko@v0.7
      - run: cd api && ko build
